#include "module_util.h"
#include "module_raylib.h"

#include <raylib.h>
#include <LuaBridge.h>

#include <vector>

struct Codepoints
{
	int* codepoints = nullptr;
	int length = 0;
};

struct UTF8String
{
	char* text = nullptr;
};

struct Vector2List
{
	std::vector<Vector2> list;
	
	void add(float x, float y) { list.push_back({x, y}); };
	void add(const Vector2& vec) { list.push_back(vec); };
	void pop() { list.pop_back(); };
	void clear() { list.clear(); };
	int size() const { return (int)list.size(); };
};

void init_raylib_module(lua_State* L)
{
	luabridge::getGlobalNamespace(L)
		.beginNamespace("Engine")
			.beginNamespace("Raylib")
				// enum
				.beginNamespace("ConfigFlags")
					.addVariable("VSYNC_HINT", ConfigFlags::FLAG_VSYNC_HINT)
					.addVariable("FULLSCREEN_MODE", ConfigFlags::FLAG_FULLSCREEN_MODE)
					.addVariable("WINDOW_RESIZABLE", ConfigFlags::FLAG_WINDOW_RESIZABLE)
					.addVariable("WINDOW_UNDECORATED", ConfigFlags::FLAG_WINDOW_UNDECORATED)
					.addVariable("WINDOW_HIDDEN", ConfigFlags::FLAG_WINDOW_HIDDEN)
					.addVariable("WINDOW_MINIMIZED", ConfigFlags::FLAG_WINDOW_MINIMIZED)
					.addVariable("WINDOW_MAXIMIZED", ConfigFlags::FLAG_WINDOW_MAXIMIZED)
					.addVariable("WINDOW_UNFOCUSED", ConfigFlags::FLAG_WINDOW_UNFOCUSED)
					.addVariable("WINDOW_TOPMOST", ConfigFlags::FLAG_WINDOW_TOPMOST)
					.addVariable("WINDOW_ALWAYS_RUN", ConfigFlags::FLAG_WINDOW_ALWAYS_RUN)
					.addVariable("WINDOW_TRANSPARENT", ConfigFlags::FLAG_WINDOW_TRANSPARENT)
					.addVariable("WINDOW_HIGHDPI", ConfigFlags::FLAG_WINDOW_HIGHDPI)
					.addVariable("WINDOW_MOUSE_PASSTHROUGH", ConfigFlags::FLAG_WINDOW_MOUSE_PASSTHROUGH)
					.addVariable("BORDERLESS_WINDOWED_MODE", ConfigFlags::FLAG_BORDERLESS_WINDOWED_MODE)
					.addVariable("MSAA_4X_HINT", ConfigFlags::FLAG_MSAA_4X_HINT)
					.addVariable("INTERLACED_HINT", ConfigFlags::FLAG_INTERLACED_HINT)
				.endNamespace()
				.beginNamespace("TraceLogLevel")
					.addVariable("ALL", TraceLogLevel::LOG_ALL)
					.addVariable("TRACE", TraceLogLevel::LOG_TRACE)
					.addVariable("DEBUG", TraceLogLevel::LOG_DEBUG)
					.addVariable("INFO", TraceLogLevel::LOG_INFO)
					.addVariable("WARNING", TraceLogLevel::LOG_WARNING)
					.addVariable("ERROR", TraceLogLevel::LOG_ERROR)
					.addVariable("FATAL", TraceLogLevel::LOG_FATAL)
					.addVariable("NONE", TraceLogLevel::LOG_NONE)
				.endNamespace()
				.beginNamespace("KeyboardKey")
					.addVariable("NULL", KeyboardKey::KEY_NULL)
					.addVariable("APOSTROPHE", KeyboardKey::KEY_APOSTROPHE)
					.addVariable("COMMA", KeyboardKey::KEY_COMMA)
					.addVariable("MINUS", KeyboardKey::KEY_MINUS)
					.addVariable("PERIOD", KeyboardKey::KEY_PERIOD)
					.addVariable("SLASH", KeyboardKey::KEY_SLASH)
					.addVariable("ZERO", KeyboardKey::KEY_ZERO)
					.addVariable("ONE", KeyboardKey::KEY_ONE)
					.addVariable("TWO", KeyboardKey::KEY_TWO)
					.addVariable("THREE", KeyboardKey::KEY_THREE)
					.addVariable("FOUR", KeyboardKey::KEY_FOUR)
					.addVariable("FIVE", KeyboardKey::KEY_FIVE)
					.addVariable("SIX", KeyboardKey::KEY_SIX)
					.addVariable("SEVEN", KeyboardKey::KEY_SEVEN)
					.addVariable("EIGHT", KeyboardKey::KEY_EIGHT)
					.addVariable("NINE", KeyboardKey::KEY_NINE)
					.addVariable("SEMICOLON", KeyboardKey::KEY_SEMICOLON)
					.addVariable("EQUAL", KeyboardKey::KEY_EQUAL)
					.addVariable("A", KeyboardKey::KEY_A)
					.addVariable("B", KeyboardKey::KEY_B)
					.addVariable("C", KeyboardKey::KEY_C)
					.addVariable("D", KeyboardKey::KEY_D)
					.addVariable("E", KeyboardKey::KEY_E)
					.addVariable("F", KeyboardKey::KEY_F)
					.addVariable("G", KeyboardKey::KEY_G)
					.addVariable("H", KeyboardKey::KEY_H)
					.addVariable("I", KeyboardKey::KEY_I)
					.addVariable("J", KeyboardKey::KEY_J)
					.addVariable("K", KeyboardKey::KEY_K)
					.addVariable("L", KeyboardKey::KEY_L)
					.addVariable("M", KeyboardKey::KEY_M)
					.addVariable("N", KeyboardKey::KEY_N)
					.addVariable("O", KeyboardKey::KEY_O)
					.addVariable("P", KeyboardKey::KEY_P)
					.addVariable("Q", KeyboardKey::KEY_Q)
					.addVariable("R", KeyboardKey::KEY_R)
					.addVariable("S", KeyboardKey::KEY_S)
					.addVariable("T", KeyboardKey::KEY_T)
					.addVariable("U", KeyboardKey::KEY_U)
					.addVariable("V", KeyboardKey::KEY_V)
					.addVariable("W", KeyboardKey::KEY_W)
					.addVariable("X", KeyboardKey::KEY_X)
					.addVariable("Y", KeyboardKey::KEY_Y)
					.addVariable("Z", KeyboardKey::KEY_Z)
					.addVariable("LEFT_BRACKET", KeyboardKey::KEY_LEFT_BRACKET)
					.addVariable("BACKSLASH", KeyboardKey::KEY_BACKSLASH)
					.addVariable("RIGHT_BRACKET", KeyboardKey::KEY_RIGHT_BRACKET)
					.addVariable("GRAVE", KeyboardKey::KEY_GRAVE)
					.addVariable("SPACE", KeyboardKey::KEY_SPACE)
					.addVariable("ESCAPE", KeyboardKey::KEY_ESCAPE)
					.addVariable("ENTER", KeyboardKey::KEY_ENTER)
					.addVariable("TAB", KeyboardKey::KEY_TAB)
					.addVariable("BACKSPACE", KeyboardKey::KEY_BACKSPACE)
					.addVariable("INSERT", KeyboardKey::KEY_INSERT)
					.addVariable("DELETE", KeyboardKey::KEY_DELETE)
					.addVariable("RIGHT", KeyboardKey::KEY_RIGHT)
					.addVariable("LEFT", KeyboardKey::KEY_LEFT)
					.addVariable("DOWN", KeyboardKey::KEY_DOWN)
					.addVariable("UP", KeyboardKey::KEY_UP)
					.addVariable("PAGE_UP", KeyboardKey::KEY_PAGE_UP)
					.addVariable("PAGE_DOWN", KeyboardKey::KEY_PAGE_DOWN)
					.addVariable("HOME", KeyboardKey::KEY_HOME)
					.addVariable("END", KeyboardKey::KEY_END)
					.addVariable("CAPS_LOCK", KeyboardKey::KEY_CAPS_LOCK)
					.addVariable("SCROLL_LOCK", KeyboardKey::KEY_SCROLL_LOCK)
					.addVariable("NUM_LOCK", KeyboardKey::KEY_NUM_LOCK)
					.addVariable("PRINT_SCREEN", KeyboardKey::KEY_PRINT_SCREEN)
					.addVariable("PAUSE", KeyboardKey::KEY_PAUSE)
					.addVariable("F1", KeyboardKey::KEY_F1)
					.addVariable("F2", KeyboardKey::KEY_F2)
					.addVariable("F3", KeyboardKey::KEY_F3)
					.addVariable("F4", KeyboardKey::KEY_F4)
					.addVariable("F5", KeyboardKey::KEY_F5)
					.addVariable("F6", KeyboardKey::KEY_F6)
					.addVariable("F7", KeyboardKey::KEY_F7)
					.addVariable("F8", KeyboardKey::KEY_F8)
					.addVariable("F9", KeyboardKey::KEY_F9)
					.addVariable("F10", KeyboardKey::KEY_F10)
					.addVariable("F11", KeyboardKey::KEY_F11)
					.addVariable("F12", KeyboardKey::KEY_F12)
					.addVariable("LEFT_SHIFT", KeyboardKey::KEY_LEFT_SHIFT)
					.addVariable("LEFT_CONTROL", KeyboardKey::KEY_LEFT_CONTROL)
					.addVariable("LEFT_ALT", KeyboardKey::KEY_LEFT_ALT)
					.addVariable("LEFT_SUPER", KeyboardKey::KEY_LEFT_SUPER)
					.addVariable("RIGHT_SHIFT", KeyboardKey::KEY_RIGHT_SHIFT)
					.addVariable("RIGHT_CONTROL", KeyboardKey::KEY_RIGHT_CONTROL)
					.addVariable("RIGHT_ALT", KeyboardKey::KEY_RIGHT_ALT)
					.addVariable("RIGHT_SUPER", KeyboardKey::KEY_RIGHT_SUPER)
					.addVariable("KB_MENU", KeyboardKey::KEY_KB_MENU)
					.addVariable("KP_0", KeyboardKey::KEY_KP_0)
					.addVariable("KP_1", KeyboardKey::KEY_KP_1)
					.addVariable("KP_2", KeyboardKey::KEY_KP_2)
					.addVariable("KP_3", KeyboardKey::KEY_KP_3)
					.addVariable("KP_4", KeyboardKey::KEY_KP_4)
					.addVariable("KP_5", KeyboardKey::KEY_KP_5)
					.addVariable("KP_6", KeyboardKey::KEY_KP_6)
					.addVariable("KP_7", KeyboardKey::KEY_KP_7)
					.addVariable("KP_8", KeyboardKey::KEY_KP_8)
					.addVariable("KP_9", KeyboardKey::KEY_KP_9)
					.addVariable("KP_DECIMAL", KeyboardKey::KEY_KP_DECIMAL)
					.addVariable("KP_DIVIDE", KeyboardKey::KEY_KP_DIVIDE)
					.addVariable("KP_MULTIPLY", KeyboardKey::KEY_KP_MULTIPLY)
					.addVariable("KP_SUBTRACT", KeyboardKey::KEY_KP_SUBTRACT)
					.addVariable("KP_ADD", KeyboardKey::KEY_KP_ADD)
					.addVariable("KP_ENTER", KeyboardKey::KEY_KP_ENTER)
					.addVariable("KP_EQUAL", KeyboardKey::KEY_KP_EQUAL)
					.addVariable("BACK", KeyboardKey::KEY_BACK)
					.addVariable("MENU", KeyboardKey::KEY_MENU)
					.addVariable("VOLUME_UP", KeyboardKey::KEY_VOLUME_UP)
					.addVariable("VOLUME_DOWN", KeyboardKey::KEY_VOLUME_DOWN)
				.endNamespace()
				.beginNamespace("MouseButton")
					.addVariable("LEFT", MouseButton::MOUSE_BUTTON_LEFT)
					.addVariable("RIGHT", MouseButton::MOUSE_BUTTON_RIGHT)
					.addVariable("MIDDLE", MouseButton::MOUSE_BUTTON_MIDDLE)
					.addVariable("SIDE", MouseButton::MOUSE_BUTTON_SIDE)
					.addVariable("EXTRA", MouseButton::MOUSE_BUTTON_EXTRA)
					.addVariable("FORWARD", MouseButton::MOUSE_BUTTON_FORWARD)
					.addVariable("BACK", MouseButton::MOUSE_BUTTON_BACK)
				.endNamespace()
				.beginNamespace("MouseCursor")
					.addVariable("DEFAULT", MouseCursor::MOUSE_CURSOR_DEFAULT)
					.addVariable("ARROW", MouseCursor::MOUSE_CURSOR_ARROW)
					.addVariable("IBEAM", MouseCursor::MOUSE_CURSOR_IBEAM)
					.addVariable("CROSSHAIR", MouseCursor::MOUSE_CURSOR_CROSSHAIR)
					.addVariable("POINTING_HAND", MouseCursor::MOUSE_CURSOR_POINTING_HAND)
					.addVariable("RESIZE_EW", MouseCursor::MOUSE_CURSOR_RESIZE_EW)
					.addVariable("RESIZE_NS", MouseCursor::MOUSE_CURSOR_RESIZE_NS)
					.addVariable("RESIZE_NWSE", MouseCursor::MOUSE_CURSOR_RESIZE_NWSE)
					.addVariable("RESIZE_NESW", MouseCursor::MOUSE_CURSOR_RESIZE_NESW)
					.addVariable("RESIZE_ALL", MouseCursor::MOUSE_CURSOR_RESIZE_ALL)
					.addVariable("NOT_ALLOWED", MouseCursor::MOUSE_CURSOR_NOT_ALLOWED)
				.endNamespace()
				.beginNamespace("GamepadButton")
					.addVariable("UNKNOWN", GamepadButton::GAMEPAD_BUTTON_UNKNOWN)
					.addVariable("LEFT_FACE_UP", GamepadButton::GAMEPAD_BUTTON_LEFT_FACE_UP)
					.addVariable("LEFT_FACE_RIGHT", GamepadButton::GAMEPAD_BUTTON_LEFT_FACE_RIGHT)
					.addVariable("LEFT_FACE_DOWN", GamepadButton::GAMEPAD_BUTTON_LEFT_FACE_DOWN)
					.addVariable("LEFT_FACE_LEFT", GamepadButton::GAMEPAD_BUTTON_LEFT_FACE_LEFT)
					.addVariable("RIGHT_FACE_UP", GamepadButton::GAMEPAD_BUTTON_RIGHT_FACE_UP)
					.addVariable("RIGHT_FACE_RIGHT", GamepadButton::GAMEPAD_BUTTON_RIGHT_FACE_RIGHT)
					.addVariable("RIGHT_FACE_DOWN", GamepadButton::GAMEPAD_BUTTON_RIGHT_FACE_DOWN)
					.addVariable("RIGHT_FACE_LEFT", GamepadButton::GAMEPAD_BUTTON_RIGHT_FACE_LEFT)
					.addVariable("LEFT_TRIGGER_1", GamepadButton::GAMEPAD_BUTTON_LEFT_TRIGGER_1)
					.addVariable("LEFT_TRIGGER_2", GamepadButton::GAMEPAD_BUTTON_LEFT_TRIGGER_2)
					.addVariable("RIGHT_TRIGGER_1", GamepadButton::GAMEPAD_BUTTON_RIGHT_TRIGGER_1)
					.addVariable("RIGHT_TRIGGER_2", GamepadButton::GAMEPAD_BUTTON_RIGHT_TRIGGER_2)
					.addVariable("MIDDLE_LEFT", GamepadButton::GAMEPAD_BUTTON_MIDDLE_LEFT)
					.addVariable("MIDDLE", GamepadButton::GAMEPAD_BUTTON_MIDDLE)
					.addVariable("MIDDLE_RIGHT", GamepadButton::GAMEPAD_BUTTON_MIDDLE_RIGHT)
					.addVariable("LEFT_THUMB", GamepadButton::GAMEPAD_BUTTON_LEFT_THUMB)
					.addVariable("RIGHT_THUMB", GamepadButton::GAMEPAD_BUTTON_RIGHT_THUMB)
				.endNamespace()
				.beginNamespace("GamepadAxis")
					.addVariable("LEFT_X", GamepadAxis::GAMEPAD_AXIS_LEFT_X)
					.addVariable("LEFT_Y", GamepadAxis::GAMEPAD_AXIS_LEFT_Y)
					.addVariable("RIGHT_X", GamepadAxis::GAMEPAD_AXIS_RIGHT_X)
					.addVariable("RIGHT_Y", GamepadAxis::GAMEPAD_AXIS_RIGHT_Y)
					.addVariable("LEFT_TRIGGER", GamepadAxis::GAMEPAD_AXIS_LEFT_TRIGGER)
					.addVariable("RIGHT_TRIGGER", GamepadAxis::GAMEPAD_AXIS_RIGHT_TRIGGER)
				.endNamespace()
				.beginNamespace("MaterialMapIndex")
					.addVariable("ALBEDO", MaterialMapIndex::MATERIAL_MAP_ALBEDO)
					.addVariable("METALNESS", MaterialMapIndex::MATERIAL_MAP_METALNESS)
					.addVariable("NORMAL", MaterialMapIndex::MATERIAL_MAP_NORMAL)
					.addVariable("ROUGHNESS", MaterialMapIndex::MATERIAL_MAP_ROUGHNESS)
					.addVariable("OCCLUSION", MaterialMapIndex::MATERIAL_MAP_OCCLUSION)
					.addVariable("EMISSION", MaterialMapIndex::MATERIAL_MAP_EMISSION)
					.addVariable("HEIGHT", MaterialMapIndex::MATERIAL_MAP_HEIGHT)
					.addVariable("CUBEMAP", MaterialMapIndex::MATERIAL_MAP_CUBEMAP)
					.addVariable("IRRADIANCE", MaterialMapIndex::MATERIAL_MAP_IRRADIANCE)
					.addVariable("PREFILTER", MaterialMapIndex::MATERIAL_MAP_PREFILTER)
					.addVariable("BRDF", MaterialMapIndex::MATERIAL_MAP_BRDF)
					.addVariable("DIFFUSE", MaterialMapIndex::MATERIAL_MAP_DIFFUSE)
					.addVariable("SPECULAR", MaterialMapIndex::MATERIAL_MAP_SPECULAR)
				.endNamespace()
				.beginNamespace("ShaderLocationIndex")
					.addVariable("VERTEX_POSITION", ShaderLocationIndex::SHADER_LOC_VERTEX_POSITION)
					.addVariable("VERTEX_TEXCOORD01", ShaderLocationIndex::SHADER_LOC_VERTEX_TEXCOORD01)
					.addVariable("VERTEX_TEXCOORD02", ShaderLocationIndex::SHADER_LOC_VERTEX_TEXCOORD02)
					.addVariable("VERTEX_NORMAL", ShaderLocationIndex::SHADER_LOC_VERTEX_NORMAL)
					.addVariable("VERTEX_TANGENT", ShaderLocationIndex::SHADER_LOC_VERTEX_TANGENT)
					.addVariable("VERTEX_COLOR", ShaderLocationIndex::SHADER_LOC_VERTEX_COLOR)
					.addVariable("MATRIX_MVP", ShaderLocationIndex::SHADER_LOC_MATRIX_MVP)
					.addVariable("MATRIX_VIEW", ShaderLocationIndex::SHADER_LOC_MATRIX_VIEW)
					.addVariable("MATRIX_PROJECTION", ShaderLocationIndex::SHADER_LOC_MATRIX_PROJECTION)
					.addVariable("MATRIX_MODEL", ShaderLocationIndex::SHADER_LOC_MATRIX_MODEL)
					.addVariable("MATRIX_NORMAL", ShaderLocationIndex::SHADER_LOC_MATRIX_NORMAL)
					.addVariable("VECTOR_VIEW", ShaderLocationIndex::SHADER_LOC_VECTOR_VIEW)
					.addVariable("COLOR_DIFFUSE", ShaderLocationIndex::SHADER_LOC_COLOR_DIFFUSE)
					.addVariable("COLOR_SPECULAR", ShaderLocationIndex::SHADER_LOC_COLOR_SPECULAR)
					.addVariable("COLOR_AMBIENT", ShaderLocationIndex::SHADER_LOC_COLOR_AMBIENT)
					.addVariable("MAP_ALBEDO", ShaderLocationIndex::SHADER_LOC_MAP_ALBEDO)
					.addVariable("MAP_METALNESS", ShaderLocationIndex::SHADER_LOC_MAP_METALNESS)
					.addVariable("MAP_NORMAL", ShaderLocationIndex::SHADER_LOC_MAP_NORMAL)
					.addVariable("MAP_ROUGHNESS", ShaderLocationIndex::SHADER_LOC_MAP_ROUGHNESS)
					.addVariable("MAP_OCCLUSION", ShaderLocationIndex::SHADER_LOC_MAP_OCCLUSION)
					.addVariable("MAP_EMISSION", ShaderLocationIndex::SHADER_LOC_MAP_EMISSION)
					.addVariable("MAP_HEIGHT", ShaderLocationIndex::SHADER_LOC_MAP_HEIGHT)
					.addVariable("MAP_CUBEMAP", ShaderLocationIndex::SHADER_LOC_MAP_CUBEMAP)
					.addVariable("MAP_IRRADIANCE", ShaderLocationIndex::SHADER_LOC_MAP_IRRADIANCE)
					.addVariable("MAP_PREFILTER", ShaderLocationIndex::SHADER_LOC_MAP_PREFILTER)
					.addVariable("MAP_BRDF", ShaderLocationIndex::SHADER_LOC_MAP_BRDF)
					.addVariable("VERTEX_BONEIDS", ShaderLocationIndex::SHADER_LOC_VERTEX_BONEIDS)
					.addVariable("VERTEX_BONEWEIGHTS", ShaderLocationIndex::SHADER_LOC_VERTEX_BONEWEIGHTS)
					.addVariable("BONE_MATRICES", ShaderLocationIndex::SHADER_LOC_BONE_MATRICES)
					.addVariable("MAP_DIFFUSE", ShaderLocationIndex::SHADER_LOC_MAP_DIFFUSE)
					.addVariable("MAP_SPECULAR", ShaderLocationIndex::SHADER_LOC_MAP_SPECULAR)
				.endNamespace()
				.beginNamespace("ShaderUniformDataType")
					.addVariable("FLOAT", ShaderUniformDataType::SHADER_UNIFORM_FLOAT)
					.addVariable("VEC2", ShaderUniformDataType::SHADER_UNIFORM_VEC2)
					.addVariable("VEC3", ShaderUniformDataType::SHADER_UNIFORM_VEC3)
					.addVariable("VEC4", ShaderUniformDataType::SHADER_UNIFORM_VEC4)
					.addVariable("INT", ShaderUniformDataType::SHADER_UNIFORM_INT)
					.addVariable("IVEC2", ShaderUniformDataType::SHADER_UNIFORM_IVEC2)
					.addVariable("IVEC3", ShaderUniformDataType::SHADER_UNIFORM_IVEC3)
					.addVariable("IVEC4", ShaderUniformDataType::SHADER_UNIFORM_IVEC4)
					.addVariable("SAMPLER2D", ShaderUniformDataType::SHADER_UNIFORM_SAMPLER2D)
				.endNamespace()
				.beginNamespace("ShaderAttributeDataType")
					.addVariable("FLOAT", ShaderAttributeDataType::SHADER_ATTRIB_FLOAT)
					.addVariable("VEC2", ShaderAttributeDataType::SHADER_ATTRIB_VEC2)
					.addVariable("VEC3", ShaderAttributeDataType::SHADER_ATTRIB_VEC3)
					.addVariable("VEC4", ShaderAttributeDataType::SHADER_ATTRIB_VEC4)
				.endNamespace()
				.beginNamespace("PixelFormat")
					.addVariable("UNCOMPRESSED_GRAYSCALE", PixelFormat::PIXELFORMAT_UNCOMPRESSED_GRAYSCALE)
					.addVariable("UNCOMPRESSED_GRAY_ALPHA", PixelFormat::PIXELFORMAT_UNCOMPRESSED_GRAY_ALPHA)
					.addVariable("UNCOMPRESSED_R5G6B5", PixelFormat::PIXELFORMAT_UNCOMPRESSED_R5G6B5)
					.addVariable("UNCOMPRESSED_R8G8B8", PixelFormat::PIXELFORMAT_UNCOMPRESSED_R8G8B8)
					.addVariable("UNCOMPRESSED_R5G5B5A1", PixelFormat::PIXELFORMAT_UNCOMPRESSED_R5G5B5A1)
					.addVariable("UNCOMPRESSED_R4G4B4A4", PixelFormat::PIXELFORMAT_UNCOMPRESSED_R4G4B4A4)
					.addVariable("UNCOMPRESSED_R8G8B8A8", PixelFormat::PIXELFORMAT_UNCOMPRESSED_R8G8B8A8)
					.addVariable("UNCOMPRESSED_R32", PixelFormat::PIXELFORMAT_UNCOMPRESSED_R32)
					.addVariable("UNCOMPRESSED_R32G32B32", PixelFormat::PIXELFORMAT_UNCOMPRESSED_R32G32B32)
					.addVariable("UNCOMPRESSED_R32G32B32A32", PixelFormat::PIXELFORMAT_UNCOMPRESSED_R32G32B32A32)
					.addVariable("UNCOMPRESSED_R16", PixelFormat::PIXELFORMAT_UNCOMPRESSED_R16)
					.addVariable("UNCOMPRESSED_R16G16B16", PixelFormat::PIXELFORMAT_UNCOMPRESSED_R16G16B16)
					.addVariable("UNCOMPRESSED_R16G16B16A16", PixelFormat::PIXELFORMAT_UNCOMPRESSED_R16G16B16A16)
					.addVariable("COMPRESSED_DXT1_RGB", PixelFormat::PIXELFORMAT_COMPRESSED_DXT1_RGB)
					.addVariable("COMPRESSED_DXT1_RGBA", PixelFormat::PIXELFORMAT_COMPRESSED_DXT1_RGBA)
					.addVariable("COMPRESSED_DXT3_RGBA", PixelFormat::PIXELFORMAT_COMPRESSED_DXT3_RGBA)
					.addVariable("COMPRESSED_DXT5_RGBA", PixelFormat::PIXELFORMAT_COMPRESSED_DXT5_RGBA)
					.addVariable("COMPRESSED_ETC1_RGB", PixelFormat::PIXELFORMAT_COMPRESSED_ETC1_RGB)
					.addVariable("COMPRESSED_ETC2_RGB", PixelFormat::PIXELFORMAT_COMPRESSED_ETC2_RGB)
					.addVariable("COMPRESSED_ETC2_EAC_RGBA", PixelFormat::PIXELFORMAT_COMPRESSED_ETC2_EAC_RGBA)
					.addVariable("COMPRESSED_PVRT_RGB", PixelFormat::PIXELFORMAT_COMPRESSED_PVRT_RGB)
					.addVariable("COMPRESSED_PVRT_RGBA", PixelFormat::PIXELFORMAT_COMPRESSED_PVRT_RGBA)
					.addVariable("COMPRESSED_ASTC_4x4_RGBA", PixelFormat::PIXELFORMAT_COMPRESSED_ASTC_4x4_RGBA)
					.addVariable("COMPRESSED_ASTC_8x8_RGBA", PixelFormat::PIXELFORMAT_COMPRESSED_ASTC_8x8_RGBA)
				.endNamespace()
				.beginNamespace("TextureFilter")
					.addVariable("POINT", TextureFilter::TEXTURE_FILTER_POINT)
					.addVariable("BILINEAR", TextureFilter::TEXTURE_FILTER_BILINEAR)
					.addVariable("TRILINEAR", TextureFilter::TEXTURE_FILTER_TRILINEAR)
					.addVariable("ANISOTROPIC_4X", TextureFilter::TEXTURE_FILTER_ANISOTROPIC_4X)
					.addVariable("ANISOTROPIC_8X", TextureFilter::TEXTURE_FILTER_ANISOTROPIC_8X)
					.addVariable("ANISOTROPIC_16X", TextureFilter::TEXTURE_FILTER_ANISOTROPIC_16X)
				.endNamespace()
				.beginNamespace("TextureWrap")
					.addVariable("REPEAT", TextureWrap::TEXTURE_WRAP_REPEAT)
					.addVariable("CLAMP", TextureWrap::TEXTURE_WRAP_CLAMP)
					.addVariable("MIRROR_REPEAT", TextureWrap::TEXTURE_WRAP_MIRROR_REPEAT)
					.addVariable("MIRROR_CLAMP", TextureWrap::TEXTURE_WRAP_MIRROR_CLAMP)
				.endNamespace()
				.beginNamespace("CubemapLayout")
					.addVariable("AUTO_DETECT", CubemapLayout::CUBEMAP_LAYOUT_AUTO_DETECT)
					.addVariable("LINE_VERTICAL", CubemapLayout::CUBEMAP_LAYOUT_LINE_VERTICAL)
					.addVariable("LINE_HORIZONTAL", CubemapLayout::CUBEMAP_LAYOUT_LINE_HORIZONTAL)
					.addVariable("CROSS_THREE_BY_FOUR", CubemapLayout::CUBEMAP_LAYOUT_CROSS_THREE_BY_FOUR)
					.addVariable("CROSS_FOUR_BY_THREE", CubemapLayout::CUBEMAP_LAYOUT_CROSS_FOUR_BY_THREE)
				.endNamespace()
				.beginNamespace("FontType")
					.addVariable("DEFAULT", FontType::FONT_DEFAULT)
					.addVariable("BITMAP", FontType::FONT_BITMAP)
					.addVariable("SDF", FontType::FONT_SDF)
				.endNamespace()
				.beginNamespace("BlendMode")
					.addVariable("ALPHA", BlendMode::BLEND_ALPHA)
					.addVariable("ADDITIVE", BlendMode::BLEND_ADDITIVE)
					.addVariable("MULTIPLIED", BlendMode::BLEND_MULTIPLIED)
					.addVariable("ADD_COLORS", BlendMode::BLEND_ADD_COLORS)
					.addVariable("SUBTRACT_COLORS", BlendMode::BLEND_SUBTRACT_COLORS)
					.addVariable("ALPHA_PREMULTIPLY", BlendMode::BLEND_ALPHA_PREMULTIPLY)
					.addVariable("CUSTOM", BlendMode::BLEND_CUSTOM)
					.addVariable("CUSTOM_SEPARATE", BlendMode::BLEND_CUSTOM_SEPARATE)
				.endNamespace()
				.beginNamespace("Gesture")
					.addVariable("NONE", Gesture::GESTURE_NONE)
					.addVariable("TAP", Gesture::GESTURE_TAP)
					.addVariable("DOUBLETAP", Gesture::GESTURE_DOUBLETAP)
					.addVariable("HOLD", Gesture::GESTURE_HOLD)
					.addVariable("DRAG", Gesture::GESTURE_DRAG)
					.addVariable("SWIPE_RIGHT", Gesture::GESTURE_SWIPE_RIGHT)
					.addVariable("SWIPE_LEFT", Gesture::GESTURE_SWIPE_LEFT)
					.addVariable("SWIPE_UP", Gesture::GESTURE_SWIPE_UP)
					.addVariable("SWIPE_DOWN", Gesture::GESTURE_SWIPE_DOWN)
					.addVariable("PINCH_IN", Gesture::GESTURE_PINCH_IN)
					.addVariable("PINCH_OUT", Gesture::GESTURE_PINCH_OUT)
				.endNamespace()
				.beginNamespace("CameraMode")
					.addVariable("CUSTOM", CameraMode::CAMERA_CUSTOM)
					.addVariable("FREE", CameraMode::CAMERA_FREE)
					.addVariable("ORBITAL", CameraMode::CAMERA_ORBITAL)
					.addVariable("FIRST_PERSON", CameraMode::CAMERA_FIRST_PERSON)
					.addVariable("THIRD_PERSON", CameraMode::CAMERA_THIRD_PERSON)
				.endNamespace()
				.beginNamespace("CameraProjection")
					.addVariable("PERSPECTIVE", CameraProjection::CAMERA_PERSPECTIVE)
					.addVariable("ORTHOGRAPHIC", CameraProjection::CAMERA_ORTHOGRAPHIC)
				.endNamespace()
				.beginNamespace("NPatchLayout")
					.addVariable("NINE_PATCH", NPatchLayout::NPATCH_NINE_PATCH)
					.addVariable("THREE_PATCH_VERTICAL", NPatchLayout::NPATCH_THREE_PATCH_VERTICAL)
					.addVariable("THREE_PATCH_HORIZONTAL", NPatchLayout::NPATCH_THREE_PATCH_HORIZONTAL)
				.endNamespace()
				// usertype
				.beginClass<Codepoints>("Codepoints")
					.addProperty("length", &Codepoints::length)
				.endClass()
				.beginClass<UTF8String>("UTF8String")
					.addProperty("text", &UTF8String::text)
				.endClass()
				.beginClass<Vector2List>("Vector2List")
					.addFunction("add", luabridge::overload<float, float>(&Vector2List::add), luabridge::overload<const Vector2&>(&Vector2List::add))
					.addFunction("pop", &Vector2List::pop)
					.addFunction("clear", &Vector2List::clear)
					.addFunction("size", &Vector2List::size)
					.addConstructor<void()>()
				.endClass()
				.beginClass<Vector2>("Vector2")
					.addProperty("x", &Vector2::x, &Vector2::x)
					.addProperty("y", &Vector2::y, &Vector2::y)
					.addConstructor(+[](void* ptr, float x, float y) { return new (ptr) Vector2({ x, y }); },
						+[](void* ptr) { return new (ptr) Vector2(); })
				.endClass()
				.beginClass<Vector3>("Vector3")
					.addProperty("x", &Vector3::x, &Vector3::x)
					.addProperty("y", &Vector3::y, &Vector3::y)
					.addProperty("z", &Vector3::z, &Vector3::z)
					.addConstructor(+[](void* ptr, float x, float y, float z) { return new (ptr) Vector3({ x, y, z }); },
						+[](void* ptr) { return new (ptr) Vector3(); })
				.endClass()
				.beginClass<Vector4>("Vector4")
					.addProperty("x", &Vector4::x, &Vector4::x)
					.addProperty("y", &Vector4::y, &Vector4::y)
					.addProperty("z", &Vector4::z, &Vector4::z)
					.addProperty("w", &Vector4::w, &Vector4::w)
					.addConstructor(+[](void* ptr, float x, float y, float z, float w) { return new (ptr) Vector4({ x, y, z, w }); },
						+[](void* ptr) { return new (ptr) Vector4(); })
				.endClass()
				.beginClass<Matrix>("Matrix")
					.addProperty("m0", &Matrix::m0, &Matrix::m0)
					.addProperty("m4", &Matrix::m4, &Matrix::m4)
					.addProperty("m8", &Matrix::m8, &Matrix::m8)
					.addProperty("m12", &Matrix::m12, &Matrix::m12)
					.addProperty("m1", &Matrix::m1, &Matrix::m1)
					.addProperty("m5", &Matrix::m5, &Matrix::m5)
					.addProperty("m9", &Matrix::m9, &Matrix::m9)
					.addProperty("m13", &Matrix::m13, &Matrix::m13)
					.addProperty("m2", &Matrix::m2, &Matrix::m2)
					.addProperty("m6", &Matrix::m6, &Matrix::m6)
					.addProperty("m10", &Matrix::m10, &Matrix::m10)
					.addProperty("m14", &Matrix::m14, &Matrix::m14)
					.addProperty("m3", &Matrix::m3, &Matrix::m3)
					.addProperty("m7", &Matrix::m7, &Matrix::m7)
					.addProperty("m11", &Matrix::m11, &Matrix::m11)
					.addProperty("m15", &Matrix::m15, &Matrix::m15)
					.addConstructor(+[](void* ptr, float m0, float m4, float m8, float m12, float m1, float m5, float m9,
						float m13, float m2, float m6, float m10, float m14, float m3, float m7, float m11, float m15) 
						{ return new (ptr) Matrix({ m0, m4, m8, m12, m1, m5, m9, m13, m2, m6, m10, m14, m3, m7, m11, m15 }); },
						+[](void* ptr) { return new (ptr) Matrix(); })
				.endClass()
				.beginClass<Color>("Color")
					.addProperty("r", &Color::r, &Color::r)
					.addProperty("g", &Color::g, &Color::g)
					.addProperty("b", &Color::b, &Color::b)
					.addProperty("a", &Color::a, &Color::a)
					.addConstructor(+[](void* ptr, unsigned char r, unsigned char g, 
						unsigned char b, unsigned char a) { return new (ptr) Color({ r, g, b, a }); },
						+[](void* ptr) { return new (ptr) Color(); })
				.endClass()
				.beginClass<Rectangle>("Rectangle")
					.addProperty("x", &Rectangle::x, &Rectangle::x)
					.addProperty("y", &Rectangle::y, &Rectangle::y)
					.addProperty("width", &Rectangle::width, &Rectangle::width)
					.addProperty("height", &Rectangle::height, &Rectangle::height)
					.addConstructor(+[](void* ptr, float x, float y, float width, float height) 
						{ return new (ptr) Rectangle({ x, y, width, height }); },
						+[](void* ptr) { return new (ptr) Rectangle(); })
				.endClass()
				.beginClass<Image>("Image")
					.addProperty("data", &Image::data, &Image::data)
					.addProperty("width", &Image::width, &Image::width)
					.addProperty("height", &Image::height, &Image::height)
					.addProperty("mipmaps", &Image::mipmaps, &Image::mipmaps)
					.addProperty("format", &Image::format, &Image::format)
					.addConstructor<void()>()
				.endClass()
				.beginClass<Texture>("Texture")
					.addProperty("id", &Texture::id, &Texture::id)
					.addProperty("width", &Texture::width, &Texture::width)
					.addProperty("height", &Texture::height, &Texture::height)
					.addProperty("mipmaps", &Texture::mipmaps, &Texture::mipmaps)
					.addProperty("format", &Texture::format, &Texture::format)
					.addConstructor<void()>()
				.endClass()
				.beginClass<RenderTexture>("RenderTexture")
					.addProperty("id", &RenderTexture::id, &RenderTexture::id)
					.addProperty("texture", &RenderTexture::texture, &RenderTexture::texture)
					.addProperty("depth", &RenderTexture::depth, &RenderTexture::depth)
					.addConstructor<void()>()
				.endClass()
				.beginClass<NPatchInfo>("NPatchInfo")
					.addProperty("source", &NPatchInfo::source, &NPatchInfo::source)
					.addProperty("left", &NPatchInfo::left, &NPatchInfo::left)
					.addProperty("top", &NPatchInfo::top, &NPatchInfo::top)
					.addProperty("right", &NPatchInfo::right, &NPatchInfo::right)
					.addProperty("bottom", &NPatchInfo::bottom, &NPatchInfo::bottom)
					.addProperty("layout", &NPatchInfo::layout, &NPatchInfo::layout)
					.addConstructor<void()>()
				.endClass()
				.beginClass<GlyphInfo>("GlyphInfo")
					.addProperty("value", &GlyphInfo::value, &GlyphInfo::value)
					.addProperty("offsetX", &GlyphInfo::offsetX, &GlyphInfo::offsetX)
					.addProperty("offsetY", &GlyphInfo::offsetY, &GlyphInfo::offsetY)
					.addProperty("advanceX", &GlyphInfo::advanceX, &GlyphInfo::advanceX)
					.addProperty("image", &GlyphInfo::image, &GlyphInfo::image)
					.addConstructor<void()>()
				.endClass()
				.beginClass<Font>("Font")
					.addProperty("baseSize", &Font::baseSize, &Font::baseSize)
					.addProperty("glyphCount", &Font::glyphCount, &Font::glyphCount)
					.addProperty("glyphPadding", &Font::glyphPadding, &Font::glyphPadding)
					.addProperty("texture", &Font::texture, &Font::texture)
					.addProperty("recs", &Font::recs, &Font::recs)
					.addProperty("glyphs", &Font::glyphs, &Font::glyphs)
					.addConstructor<void()>()
				.endClass()
				.beginClass<Camera3D>("Camera3D")
					.addProperty("position", &Camera3D::position, &Camera3D::position)
					.addProperty("target", &Camera3D::target, &Camera3D::target)
					.addProperty("up", &Camera3D::up, &Camera3D::up)
					.addProperty("fovy", &Camera3D::fovy, &Camera3D::fovy)
					.addProperty("projection", &Camera3D::projection, &Camera3D::projection)
					.addConstructor<void()>()
				.endClass()
				.beginClass<Camera2D>("Camera2D")
					.addProperty("offset", &Camera2D::offset, &Camera2D::offset)
					.addProperty("target", &Camera2D::target, &Camera2D::target)
					.addProperty("rotation", &Camera2D::rotation, &Camera2D::rotation)
					.addProperty("zoom", &Camera2D::zoom, &Camera2D::zoom)
					.addConstructor<void()>()
				.endClass()
				.beginClass<Shader>("Shader")
					.addProperty("id", &Shader::id, &Shader::id)
					//.addProperty("locs", &Shader::locs, &Shader::locs)
					.addConstructor<void()>()
				.endClass()
				.beginClass<MaterialMap>("MaterialMap")
					.addProperty("texture", &MaterialMap::texture, &MaterialMap::texture)
					.addProperty("color", &MaterialMap::color, &MaterialMap::color)
					.addProperty("value", &MaterialMap::value, &MaterialMap::value)
					.addConstructor<void()>()
				.endClass()
				.beginClass<Material>("Material")
					.addProperty("shader", &Material::shader, &Material::shader)
					.addProperty("maps", &Material::maps, &Material::maps)
					//.addProperty("params", &Material::params, &Material::params)
					.addConstructor<void()>()
				.endClass()
				.beginClass<Transform>("Transform")
					.addProperty("translation", &Transform::translation, &Transform::translation)
					.addProperty("rotation", &Transform::rotation, &Transform::rotation)
					.addProperty("scale", &Transform::scale, &Transform::scale)
					.addConstructor<void()>()
				.endClass()
				.beginClass<Ray>("Ray")
					.addProperty("position", &Ray::position, &Ray::position)
					.addProperty("direction", &Ray::direction, &Ray::direction)
					.addConstructor<void()>()
				.endClass()
				.beginClass<Wave>("Wave")
					.addProperty("frameCount", &Wave::frameCount, &Wave::frameCount)
					.addProperty("sampleRate", &Wave::sampleRate, &Wave::sampleRate)
					.addProperty("sampleSize", &Wave::sampleSize, &Wave::sampleSize)
					.addProperty("channels", &Wave::channels, &Wave::channels)
					//.addProperty("data", &Wave::data, &Wave::data)
				.endClass()
				.beginClass<AudioStream>("AudioStream")
					//.addProperty("buffer", &AudioStream::buffer, &AudioStream::buffer)
					.addProperty("processor", &AudioStream::processor, &AudioStream::processor)
					.addProperty("sampleRate", &AudioStream::sampleRate, &AudioStream::sampleRate)
					.addProperty("sampleSize", &AudioStream::sampleSize, &AudioStream::sampleSize)
					.addProperty("channels", &AudioStream::channels, &AudioStream::channels)
				.endClass()
				.beginClass<Sound>("Sound")
					.addProperty("stream", &Sound::stream, &Sound::stream)
					.addProperty("frameCount", &Sound::frameCount, &Sound::frameCount)
				.endClass()
				.beginClass<Music>("Music")
					.addProperty("stream", &Music::stream, &Music::stream)
					.addProperty("frameCount", &Music::frameCount, &Music::frameCount)
					.addProperty("looping", &Music::looping, &Music::looping)
					.addProperty("ctxType", &Music::ctxType, &Music::ctxType)
					//.addProperty("ctxData", &Music::ctxData, &Music::ctxData)
				.endClass()
				.beginClass<FilePathList>("FilePathList")
					.addProperty("capacity", &FilePathList::capacity)
					.addProperty("count", &FilePathList::count)
					.addFunction("get", +[](const FilePathList& file_path_list, unsigned int i) -> const char*
						{
							if (i >= file_path_list.count)
								return nullptr;
							return (const char*)file_path_list.paths[i];
						})
				.endClass()
				// Window
				.addFunction("InitWindow", InitWindow)
				.addFunction("CloseWindow", CloseWindow)
				.addFunction("WindowShouldClose", WindowShouldClose)
				.addFunction("IsWindowReady", IsWindowReady)
				.addFunction("IsWindowFullscreen", IsWindowFullscreen)
				.addFunction("IsWindowHidden", IsWindowHidden)
				.addFunction("IsWindowMinimized", IsWindowMinimized)
				.addFunction("IsWindowMaximized", IsWindowMaximized)
				.addFunction("IsWindowFocused", IsWindowFocused)
				.addFunction("IsWindowResized", IsWindowResized)
				.addFunction("IsWindowState", IsWindowState)
				.addFunction("SetWindowState", SetWindowState)
				.addFunction("ClearWindowState", ClearWindowState)
				.addFunction("ToggleFullscreen", ToggleFullscreen)
				.addFunction("ToggleBorderlessWindowed", ToggleBorderlessWindowed)
				.addFunction("MaximizeWindow", MaximizeWindow)
				.addFunction("MinimizeWindow", MinimizeWindow)
				.addFunction("RestoreWindow", RestoreWindow)
				.addFunction("SetWindowIcon", SetWindowIcon)
				.addFunction("SetWindowTitle", SetWindowTitle)
				.addFunction("SetWindowPosition", SetWindowPosition)
				.addFunction("SetWindowMonitor", SetWindowMonitor)
				.addFunction("SetWindowMinSize", SetWindowMinSize)
				.addFunction("SetWindowMaxSize", SetWindowMaxSize)
				.addFunction("SetWindowSize", SetWindowSize)
				.addFunction("SetWindowOpacity", SetWindowOpacity)
				.addFunction("SetWindowFocused", SetWindowFocused)
				.addFunction("GetWindowHandle", GetWindowHandle)
				.addFunction("GetScreenWidth", GetScreenWidth)
				.addFunction("GetScreenHeight", GetScreenHeight)
				.addFunction("GetRenderWidth", GetRenderWidth)
				.addFunction("GetRenderHeight", GetRenderHeight)
				.addFunction("GetMonitorCount", GetMonitorCount)
				.addFunction("GetCurrentMonitor", GetCurrentMonitor)
				.addFunction("GetMonitorPosition", GetMonitorPosition)
				.addFunction("GetMonitorWidth", GetMonitorWidth)
				.addFunction("GetMonitorHeight", GetMonitorHeight)
				.addFunction("GetMonitorPhysicalWidth", GetMonitorPhysicalWidth)
				.addFunction("GetMonitorPhysicalHeight", GetMonitorPhysicalHeight)
				.addFunction("GetMonitorRefreshRate", GetMonitorRefreshRate)
				.addFunction("GetWindowPosition", GetWindowPosition)
				.addFunction("GetWindowScaleDPI", GetWindowScaleDPI)
				.addFunction("GetMonitorName", GetMonitorName)
				.addFunction("SetClipboardText", SetClipboardText)
				.addFunction("GetClipboardText", GetClipboardText)
				.addFunction("GetClipboardImage", GetClipboardImage)
				.addFunction("GetClipboardImage", GetClipboardImage)
				.addFunction("EnableEventWaiting", EnableEventWaiting)
				.addFunction("DisableEventWaiting", DisableEventWaiting)
				// Cursor
				.addFunction("ShowCursor", ShowCursor)
				.addFunction("HideCursor", HideCursor)
				.addFunction("IsCursorHidden", IsCursorHidden)
				.addFunction("EnableCursor", EnableCursor)
				.addFunction("DisableCursor", DisableCursor)
				.addFunction("IsCursorOnScreen", IsCursorOnScreen)
				// Drawing
				.addFunction("ClearBackground", ClearBackground)
				.addFunction("BeginDrawing", BeginDrawing)
				.addFunction("EndDrawing", EndDrawing)
				.addFunction("BeginMode2D", BeginMode2D)
				.addFunction("EndMode2D", EndMode2D)
				.addFunction("BeginMode3D", BeginMode3D)
				.addFunction("EndMode3D", EndMode3D)
				.addFunction("BeginTextureMode", BeginTextureMode)
				.addFunction("EndTextureMode", EndTextureMode)
				.addFunction("BeginShaderMode", BeginShaderMode)
				.addFunction("EndShaderMode", EndShaderMode)
				.addFunction("BeginBlendMode", BeginBlendMode)
				.addFunction("EndBlendMode", EndBlendMode)
				.addFunction("BeginScissorMode", BeginScissorMode)
				.addFunction("EndScissorMode", EndScissorMode)
				//.addFunction("BeginVrStereoMode", BeginVrStereoMode)
				//.addFunction("EndVrStereoMode", EndVrStereoMode)
				// VR
				//.addFunction("LoadVrStereoConfig", LoadVrStereoConfig)
				//.addFunction("UnloadVrStereoConfig", UnloadVrStereoConfig)
				// Shader
				.addFunction("LoadShader", LoadShader)
				.addFunction("LoadShaderFromMemory", LoadShaderFromMemory)
				.addFunction("IsShaderValid", IsShaderValid)
				.addFunction("GetShaderLocation", GetShaderLocation)
				.addFunction("GetShaderLocationAttrib", GetShaderLocationAttrib)
				.addFunction("SetShaderValue", 
					+[](Shader shader, int locIndex, float val) { SetShaderValue(shader, locIndex, &val, SHADER_UNIFORM_FLOAT); },
					+[](Shader shader, int locIndex, const Vector2& val) { SetShaderValue(shader, locIndex, &val, SHADER_UNIFORM_VEC2); },
					+[](Shader shader, int locIndex, const Vector3& val) { SetShaderValue(shader, locIndex, &val, SHADER_UNIFORM_VEC3); },
					+[](Shader shader, int locIndex, const Vector4& val) { SetShaderValue(shader, locIndex, &val, SHADER_UNIFORM_VEC4); })
				//.addFunction("SetShaderValueV", SetShaderValueV)
				.addFunction("SetShaderValueMatrix", SetShaderValueMatrix)
				.addFunction("SetShaderValueTexture", SetShaderValueTexture)
				.addFunction("UnloadShader", UnloadShader)
				// Screen-space
				.addFunction("GetMouseRay", GetMouseRay)
				.addFunction("GetScreenToWorldRay", GetScreenToWorldRay)
				.addFunction("GetScreenToWorldRayEx", GetScreenToWorldRayEx)
				.addFunction("GetWorldToScreen", GetWorldToScreen)
				.addFunction("GetWorldToScreenEx", GetWorldToScreenEx)
				.addFunction("GetWorldToScreen2D", GetWorldToScreen2D)
				.addFunction("GetScreenToWorld2D", GetScreenToWorld2D)
				.addFunction("GetCameraMatrix", GetCameraMatrix)
				.addFunction("GetCameraMatrix2D", GetCameraMatrix2D)
				// Timing
				.addFunction("SetTargetFPS", SetTargetFPS)
				.addFunction("GetFrameTime", GetFrameTime)
				.addFunction("GetTime", GetTime)
				.addFunction("GetFPS", GetFPS)
				// Custom frame control
				.addFunction("SwapScreenBuffer", SwapScreenBuffer)
				.addFunction("PollInputEvents", PollInputEvents)
				.addFunction("WaitTime", WaitTime)
				// Misc. 
				.addFunction("TakeScreenshot", TakeScreenshot)
				.addFunction("SetConfigFlags", SetConfigFlags)
				.addFunction("OpenURL", OpenURL)
				// Log
				//.addFunction("TraceLog", TraceLog)
				.addFunction("SetTraceLogLevel", SetTraceLogLevel)
				// File-system
				.addFunction("FileExists", FileExists)
				.addFunction("DirectoryExists", DirectoryExists)
				.addFunction("IsFileExtension", IsFileExtension)
				.addFunction("GetFileLength", GetFileLength)
				.addFunction("GetFileExtension", GetFileExtension)
				.addFunction("GetFileName", GetFileName)
				.addFunction("GetFileNameWithoutExt", GetFileNameWithoutExt)
				.addFunction("GetDirectoryPath", GetDirectoryPath)
				.addFunction("GetPrevDirectoryPath", GetPrevDirectoryPath)
				.addFunction("GetWorkingDirectory", GetWorkingDirectory)
				.addFunction("GetApplicationDirectory", GetApplicationDirectory)
				.addFunction("MakeDirectory", MakeDirectory)
				.addFunction("ChangeDirectory", ChangeDirectory)
				.addFunction("IsPathFile", IsPathFile)
				.addFunction("IsFileNameValid", IsFileNameValid)
				.addFunction("LoadDirectoryFiles", LoadDirectoryFiles)
				.addFunction("LoadDirectoryFilesEx", LoadDirectoryFilesEx)
				.addFunction("UnloadDirectoryFiles", UnloadDirectoryFiles)
				.addFunction("IsFileDropped", IsFileDropped)
				.addFunction("LoadDroppedFiles", LoadDroppedFiles)
				.addFunction("UnloadDroppedFiles", UnloadDroppedFiles)
				.addFunction("GetFileModTime", GetFileModTime)
				// Input
				.addFunction("IsKeyPressed", IsKeyPressed)
				.addFunction("IsKeyPressedRepeat", IsKeyPressedRepeat)
				.addFunction("IsKeyDown", IsKeyDown)
				.addFunction("IsKeyReleased", IsKeyReleased)
				.addFunction("IsKeyUp", IsKeyUp)
				.addFunction("GetKeyPressed", GetKeyPressed)
				.addFunction("GetCharPressed", GetCharPressed)
				.addFunction("SetExitKey", SetExitKey)
				.addFunction("IsGamepadAvailable", IsGamepadAvailable)
				.addFunction("GetGamepadName", GetGamepadName)
				.addFunction("IsGamepadButtonPressed", IsGamepadButtonPressed)
				.addFunction("IsGamepadButtonDown", IsGamepadButtonDown)
				.addFunction("IsGamepadButtonReleased", IsGamepadButtonReleased)
				.addFunction("IsGamepadButtonUp", IsGamepadButtonUp)
				.addFunction("GetGamepadButtonPressed", GetGamepadButtonPressed)
				.addFunction("GetGamepadAxisCount", GetGamepadAxisCount)
				.addFunction("GetGamepadAxisMovement", GetGamepadAxisMovement)
				.addFunction("SetGamepadMappings", SetGamepadMappings)
				.addFunction("SetGamepadVibration", SetGamepadVibration)
				.addFunction("IsMouseButtonPressed", IsMouseButtonPressed)
				.addFunction("IsMouseButtonDown", IsMouseButtonDown)
				.addFunction("IsMouseButtonReleased", IsMouseButtonReleased)
				.addFunction("IsMouseButtonUp", IsMouseButtonUp)
				.addFunction("GetMouseX", GetMouseX)
				.addFunction("GetMouseY", GetMouseY)
				.addFunction("GetMousePosition", GetMousePosition)
				.addFunction("GetMouseDelta", GetMouseDelta)
				.addFunction("SetMousePosition", SetMousePosition)
				.addFunction("SetMouseOffset", SetMouseOffset)
				.addFunction("SetMouseScale", SetMouseScale)
				.addFunction("GetMouseWheelMove", GetMouseWheelMove)
				.addFunction("GetMouseWheelMoveV", GetMouseWheelMoveV)
				.addFunction("SetMouseCursor", SetMouseCursor)
				.addFunction("GetTouchX", GetTouchX)
				.addFunction("GetTouchY", GetTouchY)
				.addFunction("GetTouchPosition", GetTouchPosition)
				.addFunction("GetTouchPointId", GetTouchPointId)
				.addFunction("GetTouchPointCount", GetTouchPointCount)
				.addFunction("SetGesturesEnabled", SetGesturesEnabled)
				.addFunction("IsGestureDetected", IsGestureDetected)
				.addFunction("GetGestureDetected", GetGestureDetected)
				.addFunction("GetGestureHoldDuration", GetGestureHoldDuration)
				.addFunction("GetGestureDragVector", GetGestureDragVector)
				.addFunction("GetGestureDragAngle", GetGestureDragAngle)
				.addFunction("GetGesturePinchVector", GetGesturePinchVector)
				.addFunction("GetGesturePinchAngle", GetGesturePinchAngle)
				// Camera
				.addFunction("UpdateCamera", UpdateCamera)
				.addFunction("UpdateCameraPro", UpdateCameraPro)
				// Set texture and rectangle to be used on shapes drawing
				.addFunction("SetShapesTexture", SetShapesTexture)
				.addFunction("GetShapesTexture", GetShapesTexture)
				.addFunction("GetShapesTextureRectangle", GetShapesTextureRectangle)
				// Basic shapes drawing
				.addFunction("DrawPixel", DrawPixel)
				.addFunction("DrawPixelV", DrawPixelV)
				.addFunction("DrawLine", DrawLine)
				.addFunction("DrawLineV", DrawLineV)
				.addFunction("DrawLineEx", DrawLineEx)
				.addFunction("DrawLineStrip", +[](const Vector2List& list, Color color)
					{ DrawLineStrip(list.list.data(), (int)list.list.size(), color); })
				.addFunction("DrawLineBezier", DrawLineBezier)
				.addFunction("DrawCircle", DrawCircle)
				.addFunction("DrawCircleSector", DrawCircleSector)
				.addFunction("DrawCircleSectorLines", DrawCircleSectorLines)
				.addFunction("DrawCircleGradient", DrawCircleGradient)
				.addFunction("DrawCircleV", DrawCircleV)
				.addFunction("DrawCircleLines", DrawCircleLines)
				.addFunction("DrawCircleLinesV", DrawCircleLinesV)
				.addFunction("DrawEllipse", DrawEllipse)
				.addFunction("DrawEllipseLines", DrawEllipseLines)
				.addFunction("DrawRing", DrawRing)
				.addFunction("DrawRingLines", DrawRingLines)
				.addFunction("DrawRectangle", DrawRectangle)
				.addFunction("DrawRectangleV", DrawRectangleV)
				.addFunction("DrawRectangleRec", DrawRectangleRec)
				.addFunction("DrawRectanglePro", DrawRectanglePro)
				.addFunction("DrawRectangleGradientV", DrawRectangleGradientV)
				.addFunction("DrawRectangleGradientH", DrawRectangleGradientH)
				.addFunction("DrawRectangleGradientEx", DrawRectangleGradientEx)
				.addFunction("DrawRectangleLines", DrawRectangleLines)
				.addFunction("DrawRectangleLinesEx", DrawRectangleLinesEx)
				.addFunction("DrawRectangleRounded", DrawRectangleRounded)
				.addFunction("DrawRectangleRoundedLines", DrawRectangleRoundedLines)
				.addFunction("DrawRectangleRoundedLinesEx", DrawRectangleRoundedLinesEx)
				.addFunction("DrawTriangle", DrawTriangle)
				.addFunction("DrawTriangleLines", DrawTriangleLines)
				.addFunction("DrawTriangleFan", +[](const Vector2List& list, Color color)
					{ DrawTriangleFan(list.list.data(), (int)list.list.size(), color); })
				.addFunction("DrawTriangleStrip", +[](const Vector2List& list, Color color)
					{ DrawTriangleStrip(list.list.data(), (int)list.list.size(), color); })
				.addFunction("DrawPoly", DrawPoly)
				.addFunction("DrawPolyLines", DrawPolyLines)
				.addFunction("DrawPolyLinesEx", DrawPolyLinesEx)
				// Basic shapes collision detection
				.addFunction("CheckCollisionRecs", CheckCollisionRecs)
				.addFunction("CheckCollisionCircles", CheckCollisionCircles)
				.addFunction("CheckCollisionCircleRec", CheckCollisionCircleRec)
				.addFunction("CheckCollisionCircleLine", CheckCollisionCircleLine)
				.addFunction("CheckCollisionPointRec", CheckCollisionPointRec)
				.addFunction("CheckCollisionPointCircle", CheckCollisionPointCircle)
				.addFunction("CheckCollisionPointTriangle", CheckCollisionPointTriangle)
				.addFunction("CheckCollisionPointLine", CheckCollisionPointLine)
				.addFunction("CheckCollisionPointPoly", +[](const Vector2& point, const Vector2List& list)
					{ CheckCollisionPointPoly(point, list.list.data(), (int)list.list.size()); })
				//.addFunction("CheckCollisionLines", CheckCollisionLines)
				.addFunction("GetCollisionRec", GetCollisionRec)
				// Image loading
				.addFunction("LoadImage", LoadImage)
				.addFunction("LoadImageRaw", LoadImageRaw)
				//.addFunction("LoadImageAnim", LoadImageAnim)
				//.addFunction("LoadImageAnimFromMemory", LoadImageAnimFromMemory)
				.addFunction("LoadImageFromMemory", +[](const char* filetype, const CString& buffer)
					{ return LoadImageFromMemory(filetype, (const unsigned char*)buffer.val.data(), (int)buffer.val.size()); })
				.addFunction("LoadImageFromTexture", LoadImageFromTexture)
				.addFunction("LoadImageFromScreen", LoadImageFromScreen)
				.addFunction("IsImageValid", IsImageValid)
				.addFunction("UnloadImage", UnloadImage)
				.addFunction("ExportImage", ExportImage)
				//.addFunction("ExportImageToMemory", ExportImageToMemory)
				.addFunction("ExportImageAsCode", ExportImageAsCode)
				// Image generation
				.addFunction("GenImageColor", GenImageColor)
				.addFunction("GenImageGradientLinear", GenImageGradientLinear)
				.addFunction("GenImageGradientRadial", GenImageGradientRadial)
				.addFunction("GenImageGradientSquare", GenImageGradientSquare)
				.addFunction("GenImageChecked", GenImageChecked)
				.addFunction("GenImageWhiteNoise", GenImageWhiteNoise)
				.addFunction("GenImagePerlinNoise", GenImagePerlinNoise)
				.addFunction("GenImageCellular", GenImageCellular)
				.addFunction("GenImageText", GenImageText)
				// Image manipulation
				.addFunction("ImageCopy", ImageCopy)
				.addFunction("ImageFromImage", ImageFromImage)
				.addFunction("ImageFromChannel", ImageFromChannel)
				.addFunction("ImageText", ImageText)
				.addFunction("ImageTextEx", ImageTextEx)
				.addFunction("ImageFormat", ImageFormat)
				.addFunction("ImageToPOT", ImageToPOT)
				.addFunction("ImageCrop", ImageCrop)
				.addFunction("ImageAlphaCrop", ImageAlphaCrop)
				.addFunction("ImageAlphaClear", ImageAlphaClear)
				.addFunction("ImageAlphaMask", ImageAlphaMask)
				.addFunction("ImageAlphaPremultiply", ImageAlphaPremultiply)
				.addFunction("ImageBlurGaussian", ImageBlurGaussian)
				//.addFunction("ImageKernelConvolution", ImageKernelConvolution)
				.addFunction("ImageResize", ImageResize)
				.addFunction("ImageResizeNN", ImageResizeNN)
				.addFunction("ImageResizeCanvas", ImageResizeCanvas)
				.addFunction("ImageDither", ImageDither)
				.addFunction("ImageFlipVertical", ImageFlipVertical)
				.addFunction("ImageFlipHorizontal", ImageFlipHorizontal)
				.addFunction("ImageRotate", ImageRotate)
				.addFunction("ImageRotateCW", ImageRotateCW)
				.addFunction("ImageRotateCCW", ImageRotateCCW)
				.addFunction("ImageColorTint", ImageColorTint)
				.addFunction("ImageColorInvert", ImageColorInvert)
				.addFunction("ImageColorGrayscale", ImageColorGrayscale)
				.addFunction("ImageColorContrast", ImageColorContrast)
				.addFunction("ImageColorBrightness", ImageColorBrightness)
				.addFunction("ImageColorReplace", ImageColorReplace)
				//.addFunction("LoadImageColors", LoadImageColors)
				//.addFunction("LoadImagePalette", LoadImagePalette)
				//.addFunction("UnloadImageColors", UnloadImageColors)
				//.addFunction("UnloadImagePalette", UnloadImagePalette)
				.addFunction("GetImageAlphaBorder", GetImageAlphaBorder)
				.addFunction("GetImageColor", GetImageColor)
				// Texture loading
				.addFunction("LoadTexture", LoadTexture)
				.addFunction("LoadTextureFromImage", LoadTextureFromImage)
				.addFunction("LoadTextureCubemap", LoadTextureCubemap)
				.addFunction("LoadRenderTexture", LoadRenderTexture)
				.addFunction("IsTextureValid", IsTextureValid)
				.addFunction("UnloadTexture", UnloadTexture)
				.addFunction("IsRenderTextureValid", IsRenderTextureValid)
				.addFunction("UnloadRenderTexture", UnloadRenderTexture)
				.addFunction("UpdateTexture", UpdateTexture)
				.addFunction("UpdateTextureRec", UpdateTextureRec)
				// Texture configuration
				.addFunction("GenTextureMipmaps", GenTextureMipmaps)
				.addFunction("SetTextureFilter", SetTextureFilter)
				.addFunction("SetTextureWrap", SetTextureWrap)
				// Texture drawing
				.addFunction("DrawTexture", DrawTexture)
				.addFunction("DrawTextureV", DrawTextureV)
				.addFunction("DrawTextureEx", DrawTextureEx)
				.addFunction("DrawTextureRec", DrawTextureRec)
				.addFunction("DrawTexturePro", DrawTexturePro)
				.addFunction("DrawTextureNPatch", DrawTextureNPatch)
				// Font loading/unloading
				.addFunction("GetFontDefault", GetFontDefault)
				.addFunction("LoadFont", LoadFont)
				.addFunction("LoadFontEx", +[](const char* fileName, int fontSize, Codepoints codepoints)
					{ return LoadFontEx(fileName, fontSize, codepoints.codepoints, codepoints.length); })
				.addFunction("LoadFontFromImage", LoadFontFromImage)
				//.addFunction("LoadFontFromMemory", LoadFontFromMemory)
				.addFunction("IsFontValid", IsFontValid)
				//.addFunction("LoadFontData", LoadFontData)
				//.addFunction("GenImageFontAtlas", GenImageFontAtlas)
				//.addFunction("UnloadFontData", UnloadFontData)
				.addFunction("UnloadFont", UnloadFont)
				.addFunction("ExportFontAsCode", ExportFontAsCode)
				// Text drawing
				.addFunction("DrawFPS", DrawFPS)
				.addFunction("DrawText", DrawText)
				.addFunction("DrawTextEx", DrawTextEx)
				.addFunction("DrawTextPro", DrawTextPro)
				.addFunction("DrawTextCodepoint", DrawTextCodepoint)
				//.addFunction("DrawTextCodepoints", DrawTextCodepoints)
				// Text font info
				.addFunction("SetTextLineSpacing", SetTextLineSpacing)
				.addFunction("MeasureText", MeasureText)
				.addFunction("MeasureTextEx", MeasureTextEx)
				.addFunction("GetGlyphIndex", GetGlyphIndex)
				.addFunction("GetGlyphInfo", GetGlyphInfo)
				.addFunction("GetGlyphAtlasRec", GetGlyphAtlasRec)
				// Text codepoints management
				.addFunction("LoadUTF8", +[](const Codepoints codepoints)
					{ return UTF8String{ LoadUTF8(codepoints.codepoints, codepoints.length) }; })
				.addFunction("UnloadUTF8", +[](UTF8String utf8_str) { UnloadUTF8(utf8_str.text); })
				.addFunction("LoadCodepoints", +[](const char* text) 
					{
						Codepoints codepoints; 
						codepoints.codepoints = LoadCodepoints(text, &codepoints.length);
						return codepoints;
					})
				.addFunction("UnloadCodepoints", +[](Codepoints codepoints) 
					{ UnloadCodepoints(codepoints.codepoints); })
				.addFunction("GetCodepointCount", GetCodepointCount)
				//.addFunction("GetCodepoint", GetCodepoint)
				//.addFunction("GetCodepointNext", GetCodepointNext)
				//.addFunction("GetCodepointPrevious", GetCodepointPrevious)
				//.addFunction("CodepointToUTF8", CodepointToUTF8)
				// Audio Loading and Playing
				.addFunction("InitAudioDevice", InitAudioDevice)
				.addFunction("CloseAudioDevice", CloseAudioDevice)
				.addFunction("IsAudioDeviceReady", IsAudioDeviceReady)
				.addFunction("SetMasterVolume", SetMasterVolume)
				.addFunction("GetMasterVolume", GetMasterVolume)
				// Wave/Sound loading/unloading
				.addFunction("LoadWave", LoadWave)
				.addFunction("LoadWaveFromMemory", +[](const char* fileType, const char* fileData, int dataSize)
					{ LoadWaveFromMemory(fileType, (const unsigned char*)fileData, dataSize); })
				.addFunction("IsWaveValid", IsWaveValid)
				.addFunction("LoadSound", LoadSound)
				.addFunction("LoadSoundFromWave", LoadSoundFromWave)
				.addFunction("LoadSoundAlias", LoadSoundAlias)
				.addFunction("IsSoundValid", IsSoundValid)
				//.addFunction("UpdateSound", UpdateSound)
				.addFunction("UnloadWave", UnloadWave)
				.addFunction("UnloadSound", UnloadSound)
				.addFunction("UnloadSoundAlias", UnloadSoundAlias)
				.addFunction("ExportWave", ExportWave)
				.addFunction("ExportWaveAsCode", ExportWaveAsCode)
				//// Wave/Sound management
				.addFunction("PlaySound", PlaySound)
				.addFunction("StopSound", StopSound)
				.addFunction("PauseSound", PauseSound)
				.addFunction("ResumeSound", ResumeSound)
				.addFunction("IsSoundPlaying", IsSoundPlaying)
				.addFunction("SetSoundVolume", SetSoundVolume)
				.addFunction("SetSoundPitch", SetSoundPitch)
				.addFunction("SetSoundPan", SetSoundPan)
				.addFunction("WaveCopy", WaveCopy)
				.addFunction("WaveCrop", WaveCrop)
				.addFunction("WaveFormat", WaveFormat)
				//.addFunction("LoadWaveSamples", LoadWaveSamples)
				//.addFunction("UnloadWaveSamples", UnloadWaveSamples)
				//// Music management
				.addFunction("LoadMusicStream", LoadMusicStream)
				.addFunction("LoadMusicStreamFromMemory", +[](const char* fileType, const char* data, int dataSize) 
					{ LoadMusicStreamFromMemory(fileType, (const unsigned char*) data, dataSize); })
				.addFunction("IsMusicValid", IsMusicValid)
				.addFunction("UnloadMusicStream", UnloadMusicStream)
				.addFunction("PlayMusicStream", PlayMusicStream)
				.addFunction("IsMusicStreamPlaying", IsMusicStreamPlaying)
				.addFunction("UpdateMusicStream", UpdateMusicStream)
				.addFunction("StopMusicStream", StopMusicStream)
				.addFunction("PauseMusicStream", PauseMusicStream)
				.addFunction("ResumeMusicStream", ResumeMusicStream)
				.addFunction("SeekMusicStream", SeekMusicStream)
				.addFunction("SetMusicVolume", SetMusicVolume)
				.addFunction("SetMusicPitch", SetMusicPitch)
				.addFunction("SetMusicPan", SetMusicPan)
				.addFunction("GetMusicTimeLength", GetMusicTimeLength)
				.addFunction("GetMusicTimePlayed", GetMusicTimePlayed)
			.endNamespace()
		.endNamespace();
}